# Generated by Django 4.1.6 on 2023-02-26 07:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questi', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'verbose_name': 'Ответ', 'verbose_name_plural': 'Ответы'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name': 'Вопрос', 'verbose_name_plural': 'Вопросы'},
        ),
        migrations.AlterModelOptions(
            name='theme',
            options={'verbose_name': 'Тема', 'verbose_name_plural': 'Темы'},
        ),
        migrations.AlterField(
            model_name='answer',
            name='correct',
            field=models.BooleanField(verbose_name='правильный ли ответ'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='name',
            field=models.TextField(verbose_name='ответ'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questi.question', verbose_name='вопрос'),
        ),
        migrations.AlterField(
            model_name='question',
            name='name',
            field=models.TextField(verbose_name='вопрос'),
        ),
        migrations.AlterField(
            model_name='question',
            name='theme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questi.theme', verbose_name='тема вопроса'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='name',
            field=models.TextField(verbose_name='Название темы'),
        ),
    ]
